services:
  signer-1:
    build:
      context: ../
      dockerfile: deploy/docker/Dockerfile.signer
    environment:
      - SIGNER_ID=1
      - PORT=8081
    networks:
      - minikube

  signer-2:
    build:
      context: ../
      dockerfile: deploy/docker/Dockerfile.signer
    environment:
      - SIGNER_ID=2
      - PORT=8082
    networks:
      - minikube

  signer-3:
    build:
      context: ../
      dockerfile: deploy/docker/Dockerfile.signer
    environment:
      - SIGNER_ID=3
      - PORT=8083
    networks:
      - minikube

  grpc-proxy:
    build:
      context: ../
      dockerfile: deploy/docker/Dockerfile.proxy
    environment:
      - SIGNER_1_ADDR=http://signer-1:8081
      - SIGNER_2_ADDR=http://signer-2:8082
      - SIGNER_3_ADDR=http://signer-3:8083
      - TCP_ADDR=0.0.0.0:9090
      - KEY_ID=frost-k8s-v1
    ports:
      - "9090:9090"
    depends_on:
      - signer-1
      - signer-2
      - signer-3
    networks:
      - minikube

networks:
  minikube:
    external: true
