#!/usr/bin/env bash
# repro.sh (`make repro`): reproduce everything on a FRESH Ubuntu 24.04 host from
# a fresh clone, with no manual steps:
#   1. install pinned tools, verifying signatures/checksums
#      (Docker Engine from docker.com's signed apt repo; kind, kubectl,
#      gitleaks and Go against their published SHA-256 sums)
#   2. build the kind node image from the official Kubernetes release
#   3. make test, make check-images, make e2e (certs and a fresh key are
#      generated by the e2e itself and deleted on exit)
#   4. write reports/REPRO.md: versions, commit, pass/fail and duration per step
# Needs passwordless sudo. Refuses anything but Ubuntu 24.04.
# Entry point: `make repro`, or `scripts/repro.sh` directly on a host without
# make (the Ubuntu 24.04 cloud images ship no make; this script installs it).
# If a Docker Engine is already installed and running (e.g. the preinstalled one
# on a GitHub-hosted runner, whose packages conflict with docker-ce), it is NOT
# replaced: the script detects it, records its version and origin in REPRO.md
# and continues. Docker Desktop is refused.
# REPRO_LABEL (env) names the environment in REPRO.md.
set -uo pipefail
cd "$(dirname "$0")/.."
REPO="$(pwd)"

GO_VERSION=go1.27.1
KIND_VERSION=v0.31.0
KUBECTL_VERSION=v1.36.5
GITLEAKS_VERSION=8.30.1
K8S_NODE_VERSION=v1.36.5
NODE_IMAGE=kindest/node:v1.36.5-tk8s

OUT="$REPO/reports/REPRO.md"
LOGDIR="$REPO/reports/repro-logs"
mkdir -p "$LOGDIR"
STEPS=()
FAILED=0
die() { echo "repro: FATAL: $*" >&2; exit 1; }

. /etc/os-release
[[ "$ID" == ubuntu && "$VERSION_ID" == 24.04 ]] || die "needs Ubuntu 24.04 (found $PRETTY_NAME)"
sudo -n true 2>/dev/null || die "needs passwordless sudo"
ARCH="$(dpkg --print-architecture)" # amd64 | arm64
START_ALL=$(date +%s)
LABEL="${REPRO_LABEL:-unlabelled}"
DOCKER_ORIGIN="installed by this script (docker.com apt repo, signed)"

# step NAME CMD...: run, log to reports/repro-logs/NAME.log, record result.
step() {
  local name="$1"; shift
  local s rc
  s=$(date +%s)
  echo "== repro step: $name"
  ( "$@" ) > "$LOGDIR/$name.log" 2>&1   # subshell: a step's set -e stays in the step
  rc=$?
  STEPS+=("$name|$rc|$(( $(date +%s) - s ))")
  if [[ $rc -eq 0 ]]; then echo "   PASS ($(( $(date +%s) - s ))s)"; else echo "   FAIL rc=$rc; last lines:"; tail -15 "$LOGDIR/$name.log"; FAILED=1; fi
  return $rc
}

install_base() {
  set -euo pipefail
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq ca-certificates curl jq openssl git make >/dev/null
}

install_docker() {
  set -euo pipefail
  if sudo docker info >/dev/null 2>&1; then
    if sudo docker info 2>/dev/null | grep -qi 'docker desktop'; then echo "Docker Desktop detected: refused"; exit 1; fi
    echo "existing Docker Engine detected; not replaced"
    sudo docker version --format 'server {{.Server.Version}}, client {{.Client.Version}}'
    dpkg-query -W -f '${Package} ${Version}\n' 'docker-ce' 'moby-engine' 'docker.io' 'containerd*' 2>/dev/null || true
    getent group docker >/dev/null || sudo groupadd docker
    sudo usermod -aG docker "$(id -un)"
    exit 0
  fi
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq   # apt verifies the repository signature with the key above
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  sudo usermod -aG docker "$(id -un)"
  sudo docker info --format 'docker {{.ServerVersion}} on {{.OperatingSystem}}'
}

install_bins() {
  set -euo pipefail
  local t; t="$(mktemp -d)"; cd "$t"
  curl -fsSLo kind "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-$ARCH"
  curl -fsSL "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-$ARCH.sha256sum" | awk '{print $1"  kind"}' | sha256sum -c -
  curl -fsSLo kubectl "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/$ARCH/kubectl"
  echo "$(curl -fsSL "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/$ARCH/kubectl.sha256")  kubectl" | sha256sum -c -
  local ga; ga=$([[ $ARCH == amd64 ]] && echo x64 || echo arm64)
  local gf="gitleaks_${GITLEAKS_VERSION}_linux_${ga}.tar.gz"
  curl -fsSLO "https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/$gf"
  curl -fsSL "https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks_${GITLEAKS_VERSION}_checksums.txt" | grep " $gf\$" | sha256sum -c -
  tar -xzf "$gf" gitleaks
  local gof="$GO_VERSION.linux-$ARCH.tar.gz"
  curl -fsSLO "https://go.dev/dl/$gof"
  echo "$(curl -fsSL "https://go.dev/dl/?mode=json&include=all" | jq -r --arg v "$GO_VERSION" --arg f "$gof" '.[] | select(.version==$v) | .files[] | select(.filename==$f) | .sha256')  $gof" | sha256sum -c -
  sudo install -m 0755 kind kubectl gitleaks /usr/local/bin/
  sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf "$gof"
  echo 'export PATH=/usr/local/go/bin:$PATH' | sudo tee /etc/profile.d/go.sh >/dev/null
}

# Commands that need the docker group run through `sg docker` (group membership
# is not active in this shell until a new login).
in_docker_group() { sg docker -c "export PATH=/usr/local/go/bin:\$PATH GOTOOLCHAIN=local; cd '$REPO' && $*"; }

# The node image is built from the official release server tarball. kind's own
# download (--type release) is one HTTP/2 GET with no retry or resume, and from
# some regions the CDN resets it mid-file every time (N55: EC2 ap-south-1, reset at
# 252 MiB of 340 MiB). So: fetch the tarball with resumable HTTP/1.1 range
# requests, verify it against the official .sha256 from dl.k8s.io, then
# `kind build node-image --type file`. Same artifact, now checksum-verified.
fetch_k8s_tarball() { # prints the verified path
  set -euo pipefail
  local url="https://dl.k8s.io/$K8S_NODE_VERSION/kubernetes-server-linux-$ARCH.tar.gz"
  local dir="$HOME/.cache/tk8s-repro" f want size i
  mkdir -p "$dir"; f="$dir/kubernetes-server-linux-$ARCH-$K8S_NODE_VERSION.tar.gz"
  want=$(curl -fsSIL "$url" | awk 'tolower($1)=="content-length:"{n=$2} END{gsub(/\r/,"",n); print n}')
  [ -n "$want" ] || { echo "cannot read Content-Length of $url" >&2; return 1; }
  for i in $(seq 1 30); do
    size=$(stat -c %s "$f" 2>/dev/null || echo 0)
    [ "$size" -ge "$want" ] && break
    curl -sL --http1.1 -C - -o "$f" "$url" || true
    echo "download pass $i: $(stat -c %s "$f" 2>/dev/null || echo 0) of $want bytes" >&2
  done
  echo "$(curl -fsSL "$url.sha256")  $f" | sha256sum -c - >&2
  echo "$f"
}
build_node_image() {
  local tb
  tb=$(fetch_k8s_tarball) || return 1
  echo "official tarball verified: $tb"
  in_docker_group "kind build node-image --type file '$tb' --image $NODE_IMAGE" || return 1
  in_docker_group "docker image inspect $NODE_IMAGE --format 'node image {{.Id}}'"
}

step install-base-packages install_base
step install-docker-engine install_docker
if grep -q '^existing Docker Engine detected' "$LOGDIR/install-docker-engine.log"; then
  DOCKER_ORIGIN="pre-existing on the host, detected and NOT replaced: $(grep -E '^server ' "$LOGDIR/install-docker-engine.log"); packages: $(grep -E '^(docker|moby|containerd)' "$LOGDIR/install-docker-engine.log" | tr '\n' ';')"
fi
step install-kind-kubectl-gitleaks-go install_bins
export PATH="/usr/local/go/bin:$PATH" GOTOOLCHAIN=local
step build-kind-node-image build_node_image
step make-test in_docker_group "CI=true make test"
step make-check-images in_docker_group "make check-images"
step make-e2e in_docker_group "make e2e"

# --- report ---
{
  echo "# REPRO: fresh-host reproduction"
  echo
  echo "Generated by \`scripts/repro.sh\` (\`make repro\`) on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "| Item | Value |"
  echo "|---|---|"
  echo "| environment | **$LABEL** |"
  echo "| entry point | $([ -n "${MAKELEVEL:-}" ] && echo '`make repro`' || echo '`scripts/repro.sh` (make was not installed before the run)') |"
  echo "| git commit | \`$(git rev-parse HEAD)\` ($(git rev-parse --abbrev-ref HEAD)) |"
  echo "| host | \`$(uname -a)\` |"
  echo "| OS | $PRETTY_NAME, arch $ARCH, $(nproc) CPU, $(free -h | awk '/Mem/{print $2}') RAM |"
  echo "| Go | $(/usr/local/go/bin/go version 2>/dev/null) |"
  echo "| Docker | $(sudo docker version --format '{{.Server.Version}}' 2>/dev/null); $DOCKER_ORIGIN |"
  echo "| kind | $(kind version 2>/dev/null) |"
  echo "| kubectl | $(kubectl version --client 2>/dev/null | head -1) |"
  echo "| gitleaks | $(gitleaks version 2>/dev/null) |"
  echo "| kind node image | \`$NODE_IMAGE\` $(sudo docker image inspect "$NODE_IMAGE" --format '{{.Id}}' 2>/dev/null), built from the official $K8S_NODE_VERSION release server tarball (sha256-verified against dl.k8s.io) |"
  echo "| e2e Kubernetes | $(grep -h '^kubernetes:' test/e2e/results/*/e2e.log 2>/dev/null | tail -1) |"
  echo
  echo "| Step | Result | Duration (s) | Log |"
  echo "|---|---|---:|---|"
  for s in "${STEPS[@]}"; do
    IFS='|' read -r n rc d <<<"$s"
    echo "| $n | $([[ $rc == 0 ]] && echo PASS || echo "**FAIL** (rc $rc)") | $d | \`reports/repro-logs/$n.log\` |"
  done
  echo
  echo "Total: $(( $(date +%s) - START_ALL )) s. Overall: $([[ $FAILED == 0 ]] && echo '**PASS**' || echo '**FAIL**')"
  echo
  echo "e2e summary:"
  echo '```'
  sed -n '/=== Summary/,/E2E:/p' "$LOGDIR/make-e2e.log" 2>/dev/null | grep -E '^(PASS|FAIL) |^E2E:|^git commit|^kubernetes'
  echo '```'
} > "$OUT"
cat "$OUT"
exit $FAILED
