#!/usr/bin/env bash
# repro.sh (`make repro`): reproduce everything on a FRESH Ubuntu 24.04 host from
# a fresh clone, with no manual steps:
#   1. install pinned tools, verifying signatures/checksums
#      (Docker Engine from docker.com's signed apt repo; kind, kubectl,
#      gitleaks and Go against their published SHA-256 sums)
#   2. build the kind node image from the official Kubernetes release
#   3. make test, make check-images, make e2e (certs and a fresh key are
#      generated by the e2e itself and deleted on exit)
#   4. write reports/REPRO.md: versions, commit, pass/fail and duration per step
# Needs passwordless sudo. Refuses anything but Ubuntu 24.04.
set -uo pipefail
cd "$(dirname "$0")/.."
REPO="$(pwd)"

GO_VERSION=go1.27.1
KIND_VERSION=v0.31.0
KUBECTL_VERSION=v1.36.5
GITLEAKS_VERSION=8.30.1
K8S_NODE_VERSION=v1.36.5
NODE_IMAGE=kindest/node:v1.36.5-tk8s

OUT="$REPO/reports/REPRO.md"
LOGDIR="$REPO/reports/repro-logs"
mkdir -p "$LOGDIR"
STEPS=()
FAILED=0
die() { echo "repro: FATAL: $*" >&2; exit 1; }

. /etc/os-release
[[ "$ID" == ubuntu && "$VERSION_ID" == 24.04 ]] || die "needs Ubuntu 24.04 (found $PRETTY_NAME)"
sudo -n true 2>/dev/null || die "needs passwordless sudo"
ARCH="$(dpkg --print-architecture)" # amd64 | arm64
START_ALL=$(date +%s)

# step NAME CMD...: run, log to reports/repro-logs/NAME.log, record result.
step() {
  local name="$1"; shift
  local s rc
  s=$(date +%s)
  echo "== repro step: $name"
  "$@" > "$LOGDIR/$name.log" 2>&1
  rc=$?
  STEPS+=("$name|$rc|$(( $(date +%s) - s ))")
  if [[ $rc -eq 0 ]]; then echo "   PASS ($(( $(date +%s) - s ))s)"; else echo "   FAIL rc=$rc; last lines:"; tail -15 "$LOGDIR/$name.log"; FAILED=1; fi
  return $rc
}

install_base() {
  set -euo pipefail
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq ca-certificates curl jq openssl git make >/dev/null
}

install_docker() {
  set -euo pipefail
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq   # apt verifies the repository signature with the key above
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  sudo usermod -aG docker "$(id -un)"
  sudo docker info --format 'docker {{.ServerVersion}} on {{.OperatingSystem}}'
}

install_bins() {
  set -euo pipefail
  local t; t="$(mktemp -d)"; cd "$t"
  curl -fsSLo kind "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-$ARCH"
  curl -fsSL "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-$ARCH.sha256sum" | awk '{print $1"  kind"}' | sha256sum -c -
  curl -fsSLo kubectl "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/$ARCH/kubectl"
  echo "$(curl -fsSL "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/$ARCH/kubectl.sha256")  kubectl" | sha256sum -c -
  local ga; ga=$([[ $ARCH == amd64 ]] && echo x64 || echo arm64)
  local gf="gitleaks_${GITLEAKS_VERSION}_linux_${ga}.tar.gz"
  curl -fsSLO "https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/$gf"
  curl -fsSL "https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks_${GITLEAKS_VERSION}_checksums.txt" | grep " $gf\$" | sha256sum -c -
  tar -xzf "$gf" gitleaks
  local gof="$GO_VERSION.linux-$ARCH.tar.gz"
  curl -fsSLO "https://go.dev/dl/$gof"
  echo "$(curl -fsSL "https://go.dev/dl/?mode=json&include=all" | jq -r --arg v "$GO_VERSION" --arg f "$gof" '.[] | select(.version==$v) | .files[] | select(.filename==$f) | .sha256')  $gof" | sha256sum -c -
  sudo install -m 0755 kind kubectl gitleaks /usr/local/bin/
  sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf "$gof"
  echo 'export PATH=/usr/local/go/bin:$PATH' | sudo tee /etc/profile.d/go.sh >/dev/null
}

# Commands that need the docker group run through `sg docker` (group membership
# is not active in this shell until a new login).
in_docker_group() { sg docker -c "export PATH=/usr/local/go/bin:\$PATH GOTOOLCHAIN=local; cd '$REPO' && $*"; }

build_node_image() { in_docker_group "kind build node-image --type release $K8S_NODE_VERSION --image $NODE_IMAGE && docker image inspect $NODE_IMAGE --format 'node image {{.Id}}'"; }

step install-base-packages install_base
step install-docker-engine install_docker
step install-kind-kubectl-gitleaks-go install_bins
export PATH="/usr/local/go/bin:$PATH" GOTOOLCHAIN=local
step build-kind-node-image build_node_image
step make-test in_docker_group "CI=true make test"
step make-check-images in_docker_group "make check-images"
step make-e2e in_docker_group "make e2e"

# --- report ---
{
  echo "# REPRO: fresh-host reproduction"
  echo
  echo "Generated by \`scripts/repro.sh\` (\`make repro\`) on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "| Item | Value |"
  echo "|---|---|"
  echo "| git commit | \`$(git rev-parse HEAD)\` ($(git rev-parse --abbrev-ref HEAD)) |"
  echo "| host | \`$(uname -a)\` |"
  echo "| OS | $PRETTY_NAME, arch $ARCH, $(nproc) CPU, $(free -h | awk '/Mem/{print $2}') RAM |"
  echo "| Go | $(/usr/local/go/bin/go version 2>/dev/null) |"
  echo "| Docker | $(sudo docker version --format '{{.Server.Version}}' 2>/dev/null) |"
  echo "| kind | $(kind version 2>/dev/null) |"
  echo "| kubectl | $(kubectl version --client 2>/dev/null | head -1) |"
  echo "| gitleaks | $(gitleaks version 2>/dev/null) |"
  echo "| kind node image | \`$NODE_IMAGE\` $(sudo docker image inspect "$NODE_IMAGE" --format '{{.Id}}' 2>/dev/null), built from the official $K8S_NODE_VERSION release |"
  echo "| e2e Kubernetes | $(grep -h '^kubernetes:' test/e2e/results/*/e2e.log 2>/dev/null | tail -1) |"
  echo
  echo "| Step | Result | Duration (s) | Log |"
  echo "|---|---|---:|---|"
  for s in "${STEPS[@]}"; do
    IFS='|' read -r n rc d <<<"$s"
    echo "| $n | $([[ $rc == 0 ]] && echo PASS || echo "**FAIL** (rc $rc)") | $d | \`reports/repro-logs/$n.log\` |"
  done
  echo
  echo "Total: $(( $(date +%s) - START_ALL )) s. Overall: $([[ $FAILED == 0 ]] && echo '**PASS**' || echo '**FAIL**')"
  echo
  echo "e2e summary:"
  echo '```'
  sed -n '/=== Summary/,/E2E:/p' "$LOGDIR/make-e2e.log" 2>/dev/null | grep -E '^(PASS|FAIL) |^E2E:|^git commit|^kubernetes'
  echo '```'
} > "$OUT"
cat "$OUT"
exit $FAILED
