#!/usr/bin/env bash
# gen-independence.sh MANIFEST E2E_RESULTS_DIR BENCH_RESULTS_DIR > reports/INDEPENDENCE.md
# Generates the per-signer evidence tables from deploy-manifest.json and the
# nftables rulesets saved by test/e2e/multihost.sh. No value is typed by hand.
set -euo pipefail
M="$1" E="$2" B="$3"
jqr() { jq -r "$@" "$M"; }
if [[ "$(jqr '.transport // "multipass"')" == ssh ]]; then
  exec "$(dirname "$0")/gen-independence-l2.sh" "$@"
fi
cat <<HDR
# Signer independence evidence (Phase 7B)

> **Topology: multi-VM, single physical host (Level 1). This is not infrastructure
> independence.** All four VMs run under one Multipass hypervisor on one Mac, with one
> disk, one power supply, one kernel-level host, one operator and one dealer. Level 2
> (separate regions or providers) is **NOT DONE**.

Generated by \`deploy/multihost/gen-independence.sh\` from:
- deploy manifest \`$M\` (git commit \`$(jqr .git_commit)\`, deployed $(jqr .deployed_at), kid \`$(jqr .kid)\`)
- e2e evidence \`$E\` (L1–L5 plus the coordinator-host e2e)
- benchmark \`$B\`

## Per-signer placement

| Signer | Host (VM) | IP:port | Region / provider | OS user | Share held (index only) | TLS cert SAN | Cert SHA-256 | Signer binary SHA-256 on host |
|---|---|---|---|---|---|---|---|---|
HDR
jq -r '.signers[] | "| \(.signer_id) | \(.host) | \(.ip):\(.port) | local Multipass VM on the operator Mac (same for all) | `\(.os_user)` | share-\(.share_index) only | `\(.cert_san)` | `\(.cert_sha256)` | `\(.binary_sha256_on_host)` |"' "$M"
cat <<MID

Coordinator host: \`$(jqr .coordinator_host.vm)\` (\`$(jqr .coordinator_host.ip)\`). It holds **no share**:
only \`public-meta.json\`, the CA certificate and the coordinator-side certs
(\`coordinator\`, \`coordinator-grpc\`, \`lb\`) (L4). The operator (dealer) machine is \`$(jqr .admin_ip)\`;
the ceremony directory was deleted after distribution (L4).
Signer binary: $(jqr .signer_binary.go) linux/$(jqr .signer_binary.goarch), SHA-256 \`$(jqr .signer_binary.sha256)\`,
identical on every host (L5).

## Firewall rules per signer host (nftables, default drop)

MID
for f in "$E"/nftables-*.txt; do
  vm="$(basename "$f" .txt)"; vm="${vm#nftables-}"
  echo "### $vm"
  echo '```'
  grep -E 'policy|accept|drop' "$f" | sed 's/^[[:space:]]*//'
  echo '```'
done
cat <<'TAIL'
In addition, each signer's systemd unit sets `IPAddressDeny=any` and
`IPAddressAllow=<coordinator host>`, and runs with `NoNewPrivileges`,
`ProtectSystem=strict`, `ProtectHome`, `PrivateTmp`, a system-call filter and an
empty capability set (L5). The coordinator host restricts the coordinators' own egress to
exactly the five signer IP:port pairs (`DOCKER-USER`, N4).

## What was tested

| Test | Claim | Result |
|---|---|---|
| L1 | No signer host can open TCP to another signer host's signer ports or SSH | PASS |
| L2 | SSH to signer hosts only from the operator; the operator cannot reach signer ports | PASS |
| L3 | Co-located signers (sig-a: 1,2; sig-b: 3,4) cannot read each other's share or TLS key (0600, own user) | PASS |
| L4 | Each host holds exactly its assigned share indices; the coordinator host holds none | PASS |
| L5 | Every signer runs as its own user, NoNewPrivs=1, no capabilities, ProtectSystem=strict, same binary | PASS |
| E1–E8, REQ-a–d, N1–N4 | The cluster works end to end against the remote signers | PASS |

## What this does NOT give

- **Not infrastructure independence.** One physical machine. A host compromise, hypervisor
  bug, disk theft, or power or hardware failure affects all five signers together. Anyone
  root on the Mac can read every VM's disk and memory.
- **Same operator.** One person holds SSH to every signer host (L2 grants it to the
  operator IP), so compromising the operator is compromising every signer.
- **Same software.** Every signer runs the identical binary (L5). One bug or supply-chain
  compromise in it applies to all signers at once.
- **Same dealer.** One trusted dealer generated all shares (`docs/KEY_CEREMONY.md`). A
  dishonest or compromised dealer knows the whole key.
- **Two signers per VM on sig-a and sig-b.** Compromising either of those VMs yields **two**
  shares. Two such VMs, or one of them plus sig-c, reach the threshold of 3. The per-user
  isolation (L3) only protects against compromise of a signer *process*, not of the VM.
- **Shared network path.** All signer traffic crosses the same Multipass bridge on one host.
- **Emulated WAN only.** Latency in the benchmark is `tc netem`. Measured RTTs are in
  `rtt-L*.json` and are ~32–45 ms above the configured delay (NOTES N45).
TAIL
