#!/usr/bin/env bash
# gen-independence-l2.sh MANIFEST E2E_RESULTS_DIR BENCH_RESULTS_DIR [L2_RECHECK_DIR]: Level 2 (AWS,
# one signer per region) variant of gen-independence.sh. Tables are generated from
# deploy-manifest.json, the nftables rulesets saved by test/e2e/multihost.sh, the
# SG rule log and the benchmark's measured RTT. No value is typed by hand.
set -euo pipefail
M="$1" E="$2" B="$3" RC="${4:-}"
jqr() { jq -r "$@" "$M"; }
res() {
  local r; r="$(grep -E "^(PASS|FAIL) $1:" "$E/multihost-e2e.log" | tail -1 | cut -d' ' -f1 || echo "not run")"
  if [[ "$1" == L2 && -n "$RC" && -f "$RC/multihost-e2e.log" ]]; then
    r="$r in the e2e run (a CONTROL check failed during an operator network drop, NOTES N60); re-run once: $(grep -E '^(PASS|FAIL) L2:' "$RC/multihost-e2e.log" | tail -1 | cut -d' ' -f1) (\`$RC\`)"
  fi
  echo "$r"
}
cat <<HDR
# Signer independence evidence (Phase 7B)

> **Level 2: 5 regions, one provider, one account, one operator, one build, one
> dealer.** Each signer runs on its own EC2 instance in a different AWS region. This
> removes the single physical host of Level 1, but it is still **not** independence of
> operators, providers, credentials or software (see "What this does NOT give").
> Level 1 (multi-VM on one Mac) evidence is in git history (commit b91bf19).

Generated by \`deploy/multihost/gen-independence.sh\` from:
- deploy manifest \`$M\` (git commit \`$(jqr .git_commit)\`, deployed $(jqr .deployed_at), kid \`$(jqr .kid)\`, transport $(jqr .transport))
- e2e evidence \`$E\` (L1–L5 plus the coordinator-host e2e)
- benchmark \`$B\`

## Per-signer placement

| Signer | Host | Placement (provider:AZ:type) | Reached at | Binds | OS user | Share held (index only) | TLS cert SAN | Cert SHA-256 | Signer binary SHA-256 on host | Measured RTT from coordinator (ms, TCP connect, pre-run) |
|---|---|---|---|---|---|---|---|---|---|---|
HDR
jq -r --slurpfile r "$B/rtt-pre.json" '.signers[] | . as $s | ($r[0][] | select(.signer_id == $s.signer_id) | .rtt_ms) as $rtt |
  "| \(.signer_id) | \(.host) | \(.placement) | \(.ip):\(.port) | \(.bind_ip) | `\(.os_user)` | share-\(.share_index) only | `\(.cert_san)` | `\(.cert_sha256)` | `\(.binary_sha256_on_host)` | \($rtt) |"' "$M"
cat <<MID

Coordinator host: \`$(jqr .coordinator_host.vm)\` (\`$(jqr .coordinator_host.ip)\`, Elastic IP; $(jqr .coordinator_host.placement)). It holds
**no share**: only \`public-meta.json\`, the CA certificate and the coordinator-side certs
(\`coordinator\`, \`coordinator-grpc\`, \`lb\`) (L4). The operator (dealer) machine is a single
laptop (\`$(jqr .admin_ip)\` at deploy time); the ceremony directory was deleted after
distribution (L4). Signer binary: $(jqr .signer_binary.go) linux/$(jqr .signer_binary.goarch),
SHA-256 \`$(jqr .signer_binary.sha256)\`, identical on every host (L5).

## Network controls

Two layers on every signer host:
1. **AWS security group** (per region): inbound tcp/22 only from the operator's current
   public /32; inbound signer port only from the coordinator's Elastic IP /32; nothing else.
   Every rule and every operator-IP change is logged in \`deploy/aws/state/sg-rules.txt\`
   (copied next to this report as \`sg-rules.txt\`).
2. **nftables** on the host (default drop): signer port only from the coordinator EIP. SSH
   is accepted from any source **at this layer** and restricted to the operator /32 by the
   security group, because the operator's home IP is dynamic and a host rule pinned to an
   old IP would lock the operator out (NOTES N57). This differs from Level 1, where
   nftables itself restricted SSH.

### nftables per signer host

MID
for f in "$E"/nftables-*.txt; do
  vm="$(basename "$f" .txt)"; vm="${vm#nftables-}"
  echo "#### $vm"
  echo '```'
  grep -E 'policy|accept|drop' "$f" | sed 's/^[[:space:]]*//'
  echo '```'
done
cat <<'TAIL'
In addition, each signer's systemd unit sets `IPAddressDeny=any` and
`IPAddressAllow=<coordinator EIP>`, and runs with `NoNewPrivileges`, `ProtectSystem=strict`,
`ProtectHome`, `PrivateTmp`, a system-call filter and an empty capability set (L5). The
coordinator host restricts the coordinators' own egress to exactly the five signer
IP:port pairs (`DOCKER-USER`, N4).

TAIL
cat <<TESTED
## What was tested

Results are read from \`$E/multihost-e2e.log\`.

| Test | Claim | Result |
|---|---|---|
| L1 | No signer host can open TCP to another signer host's signer port or SSH | $(res L1) |
| L2 | SSH to signer hosts only from the operator; the operator cannot reach signer ports | $(res L2) |
| L3 | Each signer's share and TLS key are 0600, owned by its own user (one signer per host) | $(res L3) |
| L4 | Each host holds exactly its assigned share index; the coordinator host holds none | $(res L4) |
| L5 | Every signer runs as its own user, NoNewPrivs=1, no capabilities, ProtectSystem=strict, same binary | $(res L5) |
| E1–E8, REQ-a–d, N1–N4 | The cluster works end to end against the remote signers | $(res E2E-MH) |

TESTED
cat <<'TAIL'
## What this does NOT give

- **One provider, one account.** All five hosts are in one AWS account. Whoever controls
  that account (its credentials, or AWS itself) can snapshot every instance's disk and
  read every share. An account compromise is a threshold compromise.
- **One operator.** One person holds the SSH key for every host and the AWS credentials.
  Compromising the operator compromises every signer.
- **One build.** Every signer runs the identical binary (L5). One bug or supply-chain
  compromise in it applies to all signers at once.
- **One dealer.** One trusted dealer generated all shares (`docs/KEY_CEREMONY.md`). A
  dishonest or compromised dealer knows the whole key.
- **Region diversity is not organisational independence.** Separate regions protect
  against a regional outage or a single-host compromise; they do not protect against the
  shared account, operator, software or dealer above.
TAIL
