#!/usr/bin/env bash
# setup-signer-host.sh: run AS ROOT on one signer host (e.g. via
# `multipass exec sig-a -- sudo bash -s -- ARGS < setup-signer-host.sh`).
# Installs signers whose files were staged in STAGE by deploy.sh, each as a
# native binary under systemd with its own system user, and a default-drop
# nftables firewall.
#
# Usage: setup-signer-host.sh STAGE COORD_IP ADMIN_IP HOST_IP ID:PORT [ID:PORT ...]
#   STAGE     directory holding frost-signer (binary), common/{public-meta.json,policy.json,ca.crt}
#             and signer-<id>/{share.json,tls.crt,tls.key} for exactly the listed ids
#   COORD_IP  the only address allowed to reach the signer ports (coordinator host)
#   ADMIN_IP  the only address allowed to SSH (operator machine)
#   HOST_IP   this host's address; signers listen on HOST_IP:PORT only
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "must run as root" >&2; exit 1; }
[[ $# -ge 5 ]] || { echo "usage: $0 STAGE COORD_IP ADMIN_IP HOST_IP ID:PORT..." >&2; exit 2; }
STAGE="$1" COORD_IP="$2" ADMIN_IP="$3" HOST_IP="$4"; shift 4
SPECS=("$@")

ip_ok() { [[ "$1" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; }
for a in "$COORD_IP" "$ADMIN_IP" "$HOST_IP"; do ip_ok "$a" || { echo "bad IP $a" >&2; exit 2; }; done

# Refuse staged material for any signer not assigned to this host.
declare -A ASSIGNED=()
PORTS=()
for spec in "${SPECS[@]}"; do
  id="${spec%%:*}" port="${spec##*:}"
  [[ "$id" =~ ^[1-9][0-9]*$ && "$port" =~ ^[0-9]+$ && "$port" -gt 1024 ]] || { echo "bad spec $spec" >&2; exit 2; }
  ASSIGNED[$id]=$port; PORTS+=("$port")
done
for d in "$STAGE"/signer-*; do
  [[ -d "$d" ]] || continue
  id="${d##*/signer-}"
  [[ -n "${ASSIGNED[$id]:-}" ]] || { echo "REFUSING: staged material for signer $id is not assigned to this host" >&2; exit 3; }
done
n_shares=$(find "$STAGE" -name share.json | wc -l)
[[ "$n_shares" -eq "${#SPECS[@]}" ]] || { echo "REFUSING: $n_shares staged shares for ${#SPECS[@]} assigned signers" >&2; exit 3; }

install -o root -g root -m 0755 "$STAGE/frost-signer" /usr/local/bin/frost-signer

for id in "${!ASSIGNED[@]}"; do
  port="${ASSIGNED[$id]}" u="frost-signer-$id" etc="/etc/frost-signer-$id" var="/var/lib/frost-signer-$id"
  src="$STAGE/signer-$id"
  for f in share.json tls.crt tls.key; do [[ -s "$src/$f" ]] || { echo "missing $src/$f" >&2; exit 3; }; done
  id "$u" >/dev/null 2>&1 || useradd --system --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin "$u"
  systemctl stop "$u.service" 2>/dev/null || true
  rm -rf "$etc" "$var"
  install -d -o root -g "$u" -m 0750 "$etc"
  install -d -o "$u" -g "$u" -m 0700 "$var"
  # Secret material: readable by this signer's user only.
  install -o "$u" -g "$u" -m 0600 "$src/share.json" "$etc/share.json"
  install -o "$u" -g "$u" -m 0600 "$src/tls.key" "$etc/tls.key"
  # Public material.
  install -o root -g "$u" -m 0640 "$src/tls.crt" "$etc/tls.crt"
  install -o root -g "$u" -m 0640 "$STAGE/common/public-meta.json" "$etc/public-meta.json"
  install -o root -g "$u" -m 0640 "$STAGE/common/policy.json" "$etc/policy.json"
  install -o root -g "$u" -m 0640 "$STAGE/common/ca.crt" "$etc/ca.crt"
  cat > "$etc/env" <<EOF
SIGNER_ID=$id
META_FILE=$etc/public-meta.json
SHARE_FILE=$etc/share.json
POLICY_FILE=$etc/policy.json
AUDIT_LOG=$var/audit.log
TLS_CERT=$etc/tls.crt
TLS_KEY=$etc/tls.key
TLS_CA=$etc/ca.crt
LISTEN_ADDR=$HOST_IP:$port
EOF
  chown root:"$u" "$etc/env"; chmod 0640 "$etc/env"
  cat > "/etc/systemd/system/$u.service" <<EOF
[Unit]
Description=frost-k8s threshold signer $id
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$u
Group=$u
EnvironmentFile=$etc/env
ExecStart=/usr/local/bin/frost-signer
Restart=on-failure
RestartSec=1
UMask=0077
# Hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ReadWritePaths=$var
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
ProcSubset=pid
RestrictAddressFamilies=AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
CapabilityBoundingSet=
AmbientCapabilities=
# Network, in addition to nftables: only the coordinator host.
IPAddressDeny=any
IPAddressAllow=$COORD_IP

[Install]
WantedBy=multi-user.target
EOF
done

# Default-drop firewall: signer ports only from COORD_IP, SSH only from ADMIN_IP.
PORTLIST=$(IFS=,; echo "${PORTS[*]}")
cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# frost-k8s signer host firewall (generated by setup-signer-host.sh)
flush ruleset
table inet frost_filter {
  chain input {
    type filter hook input priority filter; policy drop;
    iif "lo" accept
    ct state established,related accept
    ct state invalid drop
    ip saddr $ADMIN_IP tcp dport 22 accept comment "ssh from operator only"
    ip saddr $COORD_IP ip daddr $HOST_IP tcp dport { $PORTLIST } accept comment "signer ports from coordinator host only"
    ip saddr { $ADMIN_IP, $COORD_IP } icmp type echo-request accept comment "ping for RTT measurement"
    udp sport 67 udp dport 68 accept comment "DHCP lease renewal"
    icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } accept
    counter drop comment "default deny"
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
  }
  chain output {
    type filter hook output priority filter; policy accept;
  }
}
EOF
chmod 0600 /etc/nftables.conf
nft -c -f /etc/nftables.conf
nft -f /etc/nftables.conf
systemctl enable --quiet nftables

systemctl daemon-reload
for id in "${!ASSIGNED[@]}"; do
  systemctl enable --quiet "frost-signer-$id.service"
  systemctl restart "frost-signer-$id.service"
done
rm -rf "$STAGE"
sleep 1
for id in "${!ASSIGNED[@]}"; do
  systemctl is-active --quiet "frost-signer-$id.service" || { journalctl -u "frost-signer-$id" -n 20 --no-pager >&2; echo "frost-signer-$id failed to start" >&2; exit 4; }
done
echo "signers ${!ASSIGNED[*]} active on $HOST_IP ports ${PORTS[*]}; firewall loaded; binary sha256 $(sha256sum /usr/local/bin/frost-signer | cut -d' ' -f1)"
